sublimelsp/LSP-pyright

LSP-pyright.sublime-settings
Any specific reason why was this omitted?
=> fix: add "python.analysis.extraPaths" to default settings

LSP-pyright.sublime-settings, plugin.py
It's the same with `window.extract_variables()['packages']`.
I.e., `$packages` can be used instead.
@rwols As per suggestion in https://github.com/sublimelsp/LSP-pyright/issues/3#issue-669065719, I assume `LSP-pyls` is interested in this too.
=> refactor: remove redundant $sublime_packages_dir variable

LSP-pyright.sublime-settings
With latest LSP3 release we'll be able to use the same branch for both
ST3 and ST4. Both dotted settings and parsing variables are supported.
Unfortunately the schema validation will mark the ST3 properties as
deprecated.
=> Add ST3 compatibility

plugin.py
such as `server_path` in https://github.com/sublimelsp/lsp_utils/blob/cb6d400658d684f09be99af2da854f3cc2a41308/st3/lsp_utils/npm_client_handler_v2.py#L116-L120
=> fix: variables in parent additional_variables() should be added too

LSP-pyright.sublime-settings, sublime-package.json
This has been on my disk for quite a while so might need to be re-checked if it's up to date.
Also includes the new `dev_environment` option.
=> feat: add sublime-package schema

plugin.py
=> refactor: utilize latest lsp_utils

README.md
At the least, we should mention the existence of the pyrightconfig.json file, as it appears to be mandatory for this plugin to function.
Relevant issues: #13 #12
=> Mention pyrightconfig.json in the README

plugin.py, sublime-package.json
=> refactor: update plugin for Pyright 1.1.98

LSP-pyright.sublime-settings, sublime-package.json
Follows a fix in pyright: https://github.com/microsoft/pyright/commit/c07ca7057336e232eb2103e09a2c819f9fc454fa
=> fix: update python.analysis.logLevel schema and setting

LSP-pyright.sublime-settings
I'm not sure it's the right thing to do but created PR to discuss it.
I think that we should have those diagnostics enabled by default (I've seen that Pylance reports unused imports at least) as they are rather useful.
The problem with setting those is that there is also a `python.analysis.typeCheckingMode` option that can be set to either `basic` or `strict` (the default being `basic`) and if someone would set it to `strict` then having `python.analysis.diagnosticSeverityOverrides` options explicitly set would override more strict values that `strict` uses. I wonder if we are fine with that. Or are we fine with current defaults and expect the user to enable those if he wants?
=> fix: enable useful diagnostics by default

LSP-pyright.sublime-settings
With the latest version of lsp_utils a change was introduced [1] that allows using a locally
managed node runtime instead of the system one. For that to work, the "node" command
needs to use a variable.
[1] https://github.com/sublimelsp/lsp_utils/commit/403345a0c5c15e84802c712044c630a9fb236b9d
=> fix: use ${node_bin} for the node binary

LSP-pyright.sublime-settings
This language server seems to work on raw buffers. Although it's doing something weird with diagnostic publishing. Depends on https://github.com/sublimelsp/LSP/pull/1758
=> feat: enable pyright in raw buffers and ST resource files

LSP-pyright.sublime-settings, README.md
Because the branch master of `pyright` was renamed to main.
=> chore: update link to pyright, change branch from master to main

plugin.py
This commit changes the virtual environment (venv) detection logic to check if the venv binary is a valid file before returning.
This fixes a bug where LSP-pyright would detect and use a broken venv even though a valid one existed (I had a project with a broken "bak.venv" directory that contained a "pyvenv.cfg" and a broken python symlink).
=> fix: check if venv binary is valid before returning

LSP-pyright.sublime-settings, plugin.py
Apparently "this" refers to "LSP-pyright" in
https://github.com/sublimelsp/LSP-pyright/blob/56ddea390391d0f9f69e1cc0532f1da7e834ed9f/LSP-pyright.sublime-settings#L14
So if you set "pyright.dev_environment" to "sublime_text", currently it will use the Python version under which LSP-pyright runs in the plugin host, i.e. always Python 3.3. In other words, "sublime_text" is just an alias for "sublime_text_33".
Instead of using `sys.version_info`, you could just hardcode `py_ver = (3, 3)` in
https://github.com/sublimelsp/LSP-pyright/blob/56ddea390391d0f9f69e1cc0532f1da7e834ed9f/plugin.py#L42
But is it useful in any way to use the Python version of LSP-pyright here?
If you want to develop a plugin for ST4 which should run under Python 3.8, then for example this will show an error diagnostic, …
=> feat: use py version of developed plugin if "dev_environment" is "sublime_text"

plugin.py
Here is a suggestion with some enhancement for pyright's hover popups:
1. Fix horizontal rule after fenced code block accidentally being rendered as setext heading (this seems to be a bug in mdpopups or in one of its dependencies)
2. Improve rendering for some common reStructuredText field names in docstrings (ideally pyright should parse the docstrings itself and should have this built-in...)
__Before:__
__After:__
=> Apply some tweaks to content of hover popups

LSP-pyright.sublime-settings, sublime-package.json
This seems like an error in the default settings.
=> fix: remove stray whitespace in settings and adjust schema

plugin.py
- Refactor methods
- Use `shutil.which('python')` if no venv was found
- Search parent directories for python venv
=> refactor: improve resolving python path

syntaxes/pyright.sublime-syntax, syntaxes/syntax_test.pyright-syntax-test
fixes: #233
This commit uses branching to distinguish type groups and function signatures.
A function signature is of the form `(arg: type, ...) -> return-type`
=> fix: syntax highlighting of type groups and function signatures

syntaxes/Python.sublime-syntax, syntaxes/pyright.sublime-syntax, syntaxes/syntax_test.pyright-syntax-test
This PR provides required adjustments for pyright's syntax to work with https://github.com/sublimehq/Packages/pull/3736.
Unfortunately some of mensioned PRs changes break current syntax and I found no sane way around it.
=> chore: adjust syntax to python type hints

.github/workflows/schema.yml, LSP-pyright.sublime-settings, Makefile, pyproject.toml, scripts/update_schema.py, sublime-package.json
This should help with ensuring that configuration schema is up to date.
The github workflow in theory should auto-update schema in dependabot PRs but if new pyrightconfig settings are added then it will require updating the LSP part manually.
Totally untested (especially the workflow).
=> chore(ci): add script and workflow for auto-updating schema

Makefile, pyproject.toml, requirements.txt, scripts/update_schema.py
`ruff` reaches v0.2.0 today with some config renamed.
https://github.com/astral-sh/ruff/releases/tag/v0.2.0
This PR replaces `black` (code formatter) with `ruff` to reduce numerbs of dependency and improve CI performance.
=> Replace black with ruff

plugin.py
As per https://github.com/sublimelsp/repository/blob/f5e1af0a21d5dd9cd4fa76938cc8932e8d0a664b/repository.json#L742-L761 , LSP-pyright now is targetting on ST>=4148.
=> refactor: remove unneeded codes

LSP-pyright.sublime-settings, constants.py, dependencies.json, log.py, plugin.py, sublime-package.json, venv_finder.py
See plugin settings: `pyright.venv.strategies`
Resolves https://github.com/sublimelsp/LSP-pyright/issues/331
=> feat: allow users to decide the order of strategies finding venv

LSP-pyright.sublime-settings, sublime-package.json
This adds `pyright.disableTaggedHints` to the settings. Users can configure the setting in Sublime Text as follows:
```json
{
"settings": {
"pyright.disableTaggedHints": true,
}
}
```
This works in the current version of LSP-pyright in Sublime Text but it's not listed in the default settings as an option. So this pull request adds it as an option.
=> Add settings for disableTaggedHints
